import {
  UserRole,
  UserStatus,
  VendorStatus,
  DriverStatus,
  DriverAvailability,
  ProductStatus,
  OrderStatus,
  PaymentStatus,
  DeliveryStatus,
} from "@/types";

export function getInitialSeedData() {
  const now = new Date();
  const daysAgo = (d: number, hours = 0, minutes = 0) =>
    new Date(now.getTime() - d * 86400000 - hours * 3600000 - minutes * 60000).toISOString();

  const users = [
    {
      id: "usr_admin_1",
      name: "Admin Executive",
      email: "admin@delivery.com",
      role: UserRole.ADMIN,
      status: UserStatus.ACTIVE,
      phone: "+91 98765 00001",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
      createdAt: daysAgo(60),
      updatedAt: daysAgo(1),
    },
    {
      id: "usr_cust_1",
      name: "Rahul Sharma",
      email: "customer@delivery.com",
      role: UserRole.CUSTOMER,
      status: UserStatus.ACTIVE,
      phone: "+91 98765 43210",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
      createdAt: daysAgo(45),
      updatedAt: daysAgo(2),
    },
    {
      id: "usr_cust_2",
      name: "Ananya Iyer",
      email: "ananya@example.com",
      role: UserRole.CUSTOMER,
      status: UserStatus.ACTIVE,
      phone: "+91 98765 43211",
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
      createdAt: daysAgo(30),
      updatedAt: daysAgo(5),
    },
    {
      id: "usr_cust_3",
      name: "Vikram Malhotra",
      email: "vikram@example.com",
      role: UserRole.CUSTOMER,
      status: UserStatus.ACTIVE,
      phone: "+91 98765 43212",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150",
      createdAt: daysAgo(20),
      updatedAt: daysAgo(1),
    },
    {
      id: "usr_driver_1",
      name: "Suresh Kumar",
      email: "driver@delivery.com",
      role: UserRole.DRIVER,
      status: UserStatus.ACTIVE,
      phone: "+91 98765 88801",
      avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150",
      createdAt: daysAgo(50),
      updatedAt: daysAgo(0, 1),
    },
    {
      id: "usr_driver_2",
      name: "Arjun Singh",
      email: "arjun.driver@example.com",
      role: UserRole.DRIVER,
      status: UserStatus.ACTIVE,
      phone: "+91 98765 88802",
      avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150",
      createdAt: daysAgo(40),
      updatedAt: daysAgo(0, 3),
    },
    {
      id: "usr_vendor_1",
      name: "Vikrant Singh (Burger Hub)",
      email: "vendor@delivery.com",
      role: UserRole.VENDOR,
      status: UserStatus.ACTIVE,
      phone: "+91 98765 77701",
      avatarUrl: "https://images.unsplash.com/photo-1556157382-97eda2d62296?w=150",
      createdAt: daysAgo(60),
      updatedAt: daysAgo(2),
    },
    {
      id: "usr_vendor_2",
      name: "Marco Rossi (Pizzeria)",
      email: "napoli@delivery.com",
      role: UserRole.VENDOR,
      status: UserStatus.ACTIVE,
      phone: "+91 98765 77702",
      avatarUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150",
      createdAt: daysAgo(45),
      updatedAt: daysAgo(3),
    },
  ];

  const accounts = [
    {
      id: "acc_admin_1",
      userId: "usr_admin_1",
      providerId: "credential",
      accountId: "admin@delivery.com",
      password: "Password123",
    },
    {
      id: "acc_cust_1",
      userId: "usr_cust_1",
      providerId: "credential",
      accountId: "customer@delivery.com",
      password: "Password123",
    },
    {
      id: "acc_driver_1",
      userId: "usr_driver_1",
      providerId: "credential",
      accountId: "driver@delivery.com",
      password: "Password123",
    },
    {
      id: "acc_vendor_1",
      userId: "usr_vendor_1",
      providerId: "credential",
      accountId: "vendor@delivery.com",
      password: "Password123",
    },
  ];

  const categories = [
    {
      id: "cat_burgers",
      name: "Burgers & Wraps",
      slug: "burgers-wraps",
      description: "Juicy handcrafted burgers, crispy fries, and gourmet wraps",
      imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
      isActive: true,
      sortOrder: 1,
      createdAt: daysAgo(60),
      updatedAt: daysAgo(5),
    },
    {
      id: "cat_pizza",
      name: "Artisanal Pizza",
      slug: "artisanal-pizza",
      description: "Wood-fired stone oven pizzas with Italian buffalo mozzarella",
      imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400",
      isActive: true,
      sortOrder: 2,
      createdAt: daysAgo(60),
      updatedAt: daysAgo(5),
    },
    {
      id: "cat_indian",
      name: "Biryani & Curries",
      slug: "biryani-curries",
      description: "Fragrant dum biryanis, aromatic curries, and tandoori breads",
      imageUrl: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=400",
      isActive: true,
      sortOrder: 3,
      createdAt: daysAgo(60),
      updatedAt: daysAgo(5),
    },
    {
      id: "cat_asian",
      name: "Asian & Wok",
      slug: "asian-wok",
      description: "Hand-pulled ramen, steamed dim sums, and spicy pad thai",
      imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400",
      isActive: true,
      sortOrder: 4,
      createdAt: daysAgo(60),
      updatedAt: daysAgo(5),
    },
    {
      id: "cat_healthy",
      name: "Salads & Bowls",
      slug: "salads-bowls",
      description: "Fresh organic salads, macro-nutrient bowls, and detox juices",
      imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400",
      isActive: true,
      sortOrder: 5,
      createdAt: daysAgo(60),
      updatedAt: daysAgo(5),
    },
    {
      id: "cat_desserts",
      name: "Desserts & Bakery",
      slug: "desserts-bakery",
      description: "Belgian waffles, cheesecakes, croissants, and artisan coffees",
      imageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=400",
      isActive: true,
      sortOrder: 6,
      createdAt: daysAgo(60),
      updatedAt: daysAgo(5),
    },
  ];

  const vendors = [
    {
      id: "ven_burger_hub",
      userId: "usr_vendor_1",
      name: "Burger Republic",
      slug: "burger-republic",
      description: "Home of the signature smoked smashed burgers and loaded truffle fries.",
      logoUrl: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=200",
      bannerUrl: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800",
      address: "Shop 12, Galleria Mall, Sector 29",
      latitude: 28.4682,
      longitude: 77.0628,
      phone: "+91 98765 77701",
      email: "contact@burgerrepublic.in",
      status: VendorStatus.ACTIVE,
      commissionRate: 15,
      isOpen: true,
      rating: 4.8,
      totalReviews: 248,
      createdAt: daysAgo(60),
      updatedAt: daysAgo(1),
    },
    {
      id: "ven_napoli_pizza",
      userId: "usr_vendor_2",
      name: "Bella Italia Woodfired",
      slug: "bella-italia-woodfired",
      description: "Authentic Neapolitan sourdough pizzas fermented for 48 hours.",
      logoUrl: "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=200",
      bannerUrl: "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=800",
      address: "45 Cyber Hub, DLF Phase 2",
      latitude: 28.4905,
      longitude: 77.0901,
      phone: "+91 98765 77702",
      email: "ciao@bellaitalia.in",
      status: VendorStatus.ACTIVE,
      commissionRate: 18,
      isOpen: true,
      rating: 4.9,
      totalReviews: 412,
      createdAt: daysAgo(55),
      updatedAt: daysAgo(2),
    },
    {
      id: "ven_spice_bistro",
      userId: "usr_admin_1",
      name: "The Royal Dum Biryani",
      slug: "royal-dum-biryani",
      description: "Hyderabadi kacchi gosht dum biryani cooked in traditional clay handis.",
      logoUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=200",
      bannerUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800",
      address: "102 Golf Course Road, Sector 54",
      latitude: 28.4412,
      longitude: 77.1042,
      phone: "+91 98765 77703",
      email: "orders@royalbiryani.in",
      status: VendorStatus.ACTIVE,
      commissionRate: 15,
      isOpen: true,
      rating: 4.7,
      totalReviews: 189,
      createdAt: daysAgo(50),
      updatedAt: daysAgo(3),
    },
    {
      id: "ven_green_haven",
      userId: "usr_admin_1",
      name: "Green Haven Bowls & Smoothies",
      slug: "green-haven",
      description: "Nutritious farm-to-fork bowls, cold-pressed elixirs, and fresh salads.",
      logoUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=200",
      bannerUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800",
      address: "8 Horizon Center, Golf Course Road",
      latitude: 28.4552,
      longitude: 77.0988,
      phone: "+91 98765 77704",
      email: "hello@greenhaven.in",
      status: VendorStatus.ACTIVE,
      commissionRate: 12,
      isOpen: true,
      rating: 4.6,
      totalReviews: 95,
      createdAt: daysAgo(40),
      updatedAt: daysAgo(4),
    },
    {
      id: "ven_tokyo_wok",
      userId: "usr_admin_1",
      name: "Tokyo Ramen & Dumplings",
      slug: "tokyo-ramen-dumplings",
      description: "Slow-simmered rich tonkotsu broth, handcrafted ramen noodles & gyozas.",
      logoUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=200",
      bannerUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800",
      address: "18 One Horizon, Sector 43",
      latitude: 28.4589,
      longitude: 77.0954,
      phone: "+91 98765 77705",
      email: "ramen@tokyowok.in",
      status: VendorStatus.PENDING,
      commissionRate: 15,
      isOpen: false,
      rating: 4.8,
      totalReviews: 64,
      createdAt: daysAgo(10),
      updatedAt: daysAgo(1),
    },
  ];

  const products = [
    {
      id: "prd_truffle_burger",
      vendorId: "ven_burger_hub",
      categoryId: "cat_burgers",
      name: "Double Truffle Smash Burger",
      description: "Two prime smashed beef patties, black truffle mayo, caramelized shallots, aged cheddar on brioche.",
      price: 349,
      imageUrl: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
      status: ProductStatus.ACTIVE,
      isAvailable: true,
      preparationTimeMinutes: 15,
      createdAt: daysAgo(50),
      updatedAt: daysAgo(2),
    },
    {
      id: "prd_spicy_chicken_burger",
      vendorId: "ven_burger_hub",
      categoryId: "cat_burgers",
      name: "Nashville Hot Crispy Chicken",
      description: "Buttermilk fried chicken tossed in cayenne honey glaze, jalapeño slaw, house pickles.",
      price: 299,
      imageUrl: "https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?w=500",
      status: ProductStatus.ACTIVE,
      isAvailable: true,
      preparationTimeMinutes: 15,
      createdAt: daysAgo(48),
      updatedAt: daysAgo(2),
    },
    {
      id: "prd_margherita_pizza",
      vendorId: "ven_napoli_pizza",
      categoryId: "cat_pizza",
      name: "Classic Margherita D.O.P.",
      description: "San Marzano tomatoes, fresh buffalo mozzarella, hand-torn basil leaves, extra virgin olive oil.",
      price: 499,
      imageUrl: "https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=500",
      status: ProductStatus.ACTIVE,
      isAvailable: true,
      preparationTimeMinutes: 20,
      createdAt: daysAgo(45),
      updatedAt: daysAgo(1),
    },
    {
      id: "prd_truffle_funghi_pizza",
      vendorId: "ven_napoli_pizza",
      categoryId: "cat_pizza",
      name: "Wild Mushroom & Truffle Pizza",
      description: "Roasted portobello, fior di latte, white truffle cream, thyme, parmesan shavings.",
      price: 599,
      imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500",
      status: ProductStatus.ACTIVE,
      isAvailable: true,
      preparationTimeMinutes: 20,
      createdAt: daysAgo(42),
      updatedAt: daysAgo(3),
    },
    {
      id: "prd_dum_biryani",
      vendorId: "ven_spice_bistro",
      categoryId: "cat_indian",
      name: "Awadhi Gosht Dum Biryani",
      description: "Tender mutton pieces layered with aged basmati, saffron milk, brown onions, and aromatic spices.",
      price: 450,
      imageUrl: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=500",
      status: ProductStatus.ACTIVE,
      isAvailable: true,
      preparationTimeMinutes: 25,
      createdAt: daysAgo(40),
      updatedAt: daysAgo(1),
    },
    {
      id: "prd_paneer_tikka_biryani",
      vendorId: "ven_spice_bistro",
      categoryId: "cat_indian",
      name: "Smoked Paneer Tikka Biryani",
      description: "Charcoal-grilled cottage cheese cubes simmered in spiced basmati with mint raita.",
      price: 360,
      imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500",
      status: ProductStatus.ACTIVE,
      isAvailable: true,
      preparationTimeMinutes: 20,
      createdAt: daysAgo(38),
      updatedAt: daysAgo(4),
    },
    {
      id: "prd_avocado_bowl",
      vendorId: "ven_green_haven",
      categoryId: "cat_healthy",
      name: "California Avocado Quinoa Bowl",
      description: "Hass avocado, tri-color quinoa, edamame, roasted chickpeas, tahini lemon dressing.",
      price: 380,
      imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
      status: ProductStatus.ACTIVE,
      isAvailable: true,
      preparationTimeMinutes: 12,
      createdAt: daysAgo(35),
      updatedAt: daysAgo(2),
    },
    {
      id: "prd_tonkotsu_ramen",
      vendorId: "ven_tokyo_wok",
      categoryId: "cat_asian",
      name: "Signature Tonkotsu Ramen",
      description: "16-hour broth, chashu pork, marinated soft-boiled egg, nori, scallions, black garlic oil.",
      price: 480,
      imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500",
      status: ProductStatus.ACTIVE,
      isAvailable: true,
      preparationTimeMinutes: 18,
      createdAt: daysAgo(10),
      updatedAt: daysAgo(1),
    },
  ];

  const drivers = [
    {
      id: "drv_suresh",
      userId: "usr_driver_1",
      vehicleType: "MOTORCYCLE",
      vehiclePlate: "DL 03 AB 4589",
      licenseNumber: "DL1420180054321",
      status: DriverStatus.ACTIVE,
      availability: DriverAvailability.AVAILABLE,
      rating: 4.85,
      totalDeliveries: 342,
      latitude: 28.469,
      longitude: 77.065,
      createdAt: daysAgo(50),
      updatedAt: daysAgo(0, 1),
    },
    {
      id: "drv_arjun",
      userId: "usr_driver_2",
      vehicleType: "SCOOTER",
      vehiclePlate: "HR 26 CN 9821",
      licenseNumber: "HR2620190089123",
      status: DriverStatus.ACTIVE,
      availability: DriverAvailability.BUSY,
      rating: 4.92,
      totalDeliveries: 512,
      latitude: 28.485,
      longitude: 77.088,
      createdAt: daysAgo(40),
      updatedAt: daysAgo(0, 2),
    },
  ];

  const orders = [
    {
      id: "ord_1001",
      orderNumber: "ORD-9421",
      customerId: "usr_cust_1",
      vendorId: "ven_burger_hub",
      driverId: "drv_suresh",
      status: OrderStatus.DELIVERED,
      paymentStatus: PaymentStatus.PAID,
      subtotal: 648,
      deliveryFee: 40,
      platformFee: 15,
      tax: 32,
      discount: 50,
      total: 685,
      deliveryAddress: "Tower 4, Apt 802, Palm Springs, Golf Course Road, Gurugram",
      specialInstructions: "Please leave at security front desk.",
      createdAt: daysAgo(0, 4),
      updatedAt: daysAgo(0, 3),
    },
    {
      id: "ord_1002",
      orderNumber: "ORD-9422",
      customerId: "usr_cust_2",
      vendorId: "ven_napoli_pizza",
      driverId: "drv_arjun",
      status: OrderStatus.OUT_FOR_DELIVERY,
      paymentStatus: PaymentStatus.PAID,
      subtotal: 1098,
      deliveryFee: 50,
      platformFee: 15,
      tax: 55,
      discount: 0,
      total: 1218,
      deliveryAddress: "Villa 22, Magnolias, DLF Phase 5, Gurugram",
      specialInstructions: "Ring bell twice, do not call phone.",
      createdAt: daysAgo(0, 1),
      updatedAt: daysAgo(0, 0, 30),
    },
    {
      id: "ord_1003",
      orderNumber: "ORD-9423",
      customerId: "usr_cust_3",
      vendorId: "ven_spice_bistro",
      driverId: null,
      status: OrderStatus.PREPARING,
      paymentStatus: PaymentStatus.PAID,
      subtotal: 810,
      deliveryFee: 40,
      platformFee: 15,
      tax: 41,
      discount: 80,
      total: 826,
      deliveryAddress: "Flat 503, Silver Oaks, DLF Phase 1, Gurugram",
      specialInstructions: "Extra raita and onions requested.",
      createdAt: daysAgo(0, 0, 45),
      updatedAt: daysAgo(0, 0, 20),
    },
    {
      id: "ord_1004",
      orderNumber: "ORD-9424",
      customerId: "usr_cust_1",
      vendorId: "ven_green_haven",
      driverId: null,
      status: OrderStatus.PENDING,
      paymentStatus: PaymentStatus.PAID,
      subtotal: 380,
      deliveryFee: 30,
      platformFee: 15,
      tax: 19,
      discount: 0,
      total: 444,
      deliveryAddress: "Tower 4, Apt 802, Palm Springs, Golf Course Road, Gurugram",
      specialInstructions: "",
      createdAt: daysAgo(0, 0, 10),
      updatedAt: daysAgo(0, 0, 10),
    },
    {
      id: "ord_1005",
      orderNumber: "ORD-9415",
      customerId: "usr_cust_2",
      vendorId: "ven_burger_hub",
      driverId: "drv_suresh",
      status: OrderStatus.DELIVERED,
      paymentStatus: PaymentStatus.PAID,
      subtotal: 598,
      deliveryFee: 40,
      platformFee: 15,
      tax: 30,
      discount: 0,
      total: 683,
      deliveryAddress: "Villa 22, Magnolias, DLF Phase 5, Gurugram",
      specialInstructions: "",
      createdAt: daysAgo(1, 6),
      updatedAt: daysAgo(1, 5),
    },
    {
      id: "ord_1006",
      orderNumber: "ORD-9402",
      customerId: "usr_cust_3",
      vendorId: "ven_napoli_pizza",
      driverId: "drv_arjun",
      status: OrderStatus.DELIVERED,
      paymentStatus: PaymentStatus.PAID,
      subtotal: 499,
      deliveryFee: 40,
      platformFee: 15,
      tax: 25,
      discount: 50,
      total: 529,
      deliveryAddress: "Flat 503, Silver Oaks, DLF Phase 1, Gurugram",
      specialInstructions: "",
      createdAt: daysAgo(2, 4),
      updatedAt: daysAgo(2, 3),
    },
    {
      id: "ord_1007",
      orderNumber: "ORD-9390",
      customerId: "usr_cust_1",
      vendorId: "ven_spice_bistro",
      driverId: "drv_suresh",
      status: OrderStatus.DELIVERED,
      paymentStatus: PaymentStatus.PAID,
      subtotal: 900,
      deliveryFee: 50,
      platformFee: 15,
      tax: 45,
      discount: 100,
      total: 910,
      deliveryAddress: "Tower 4, Apt 802, Palm Springs, Golf Course Road, Gurugram",
      specialInstructions: "",
      createdAt: daysAgo(3, 8),
      updatedAt: daysAgo(3, 7),
    },
  ];

  const orderItems = [
    {
      id: "oit_1",
      orderId: "ord_1001",
      productId: "prd_truffle_burger",
      name: "Double Truffle Smash Burger",
      price: 349,
      quantity: 1,
      total: 349,
    },
    {
      id: "oit_2",
      orderId: "ord_1001",
      productId: "prd_spicy_chicken_burger",
      name: "Nashville Hot Crispy Chicken",
      price: 299,
      quantity: 1,
      total: 299,
    },
    {
      id: "oit_3",
      orderId: "ord_1002",
      productId: "prd_margherita_pizza",
      name: "Classic Margherita D.O.P.",
      price: 499,
      quantity: 1,
      total: 499,
    },
    {
      id: "oit_4",
      orderId: "ord_1002",
      productId: "prd_truffle_funghi_pizza",
      name: "Wild Mushroom & Truffle Pizza",
      price: 599,
      quantity: 1,
      total: 599,
    },
    {
      id: "oit_5",
      orderId: "ord_1003",
      productId: "prd_dum_biryani",
      name: "Awadhi Gosht Dum Biryani",
      price: 450,
      quantity: 1,
      total: 450,
    },
    {
      id: "oit_6",
      orderId: "ord_1003",
      productId: "prd_paneer_tikka_biryani",
      name: "Smoked Paneer Tikka Biryani",
      price: 360,
      quantity: 1,
      total: 360,
    },
    {
      id: "oit_7",
      orderId: "ord_1004",
      productId: "prd_avocado_bowl",
      name: "California Avocado Quinoa Bowl",
      price: 380,
      quantity: 1,
      total: 380,
    },
    {
      id: "oit_8",
      orderId: "ord_1005",
      productId: "prd_spicy_chicken_burger",
      name: "Nashville Hot Crispy Chicken",
      price: 299,
      quantity: 2,
      total: 598,
    },
    {
      id: "oit_9",
      orderId: "ord_1006",
      productId: "prd_margherita_pizza",
      name: "Classic Margherita D.O.P.",
      price: 499,
      quantity: 1,
      total: 499,
    },
    {
      id: "oit_10",
      orderId: "ord_1007",
      productId: "prd_dum_biryani",
      name: "Awadhi Gosht Dum Biryani",
      price: 450,
      quantity: 2,
      total: 900,
    },
  ];

  const payments = [
    {
      id: "pay_1001",
      orderId: "ord_1001",
      amount: 685,
      currency: "INR",
      status: PaymentStatus.PAID,
      method: "UPI",
      transactionId: "pay_upi_98241029",
      paidAt: daysAgo(0, 4),
      createdAt: daysAgo(0, 4),
      updatedAt: daysAgo(0, 4),
    },
    {
      id: "pay_1002",
      orderId: "ord_1002",
      amount: 1218,
      currency: "INR",
      status: PaymentStatus.PAID,
      method: "CARD",
      transactionId: "pay_card_48102941",
      paidAt: daysAgo(0, 1),
      createdAt: daysAgo(0, 1),
      updatedAt: daysAgo(0, 1),
    },
    {
      id: "pay_1003",
      orderId: "ord_1003",
      amount: 826,
      currency: "INR",
      status: PaymentStatus.PAID,
      method: "UPI",
      transactionId: "pay_upi_11209481",
      paidAt: daysAgo(0, 0, 45),
      createdAt: daysAgo(0, 0, 45),
      updatedAt: daysAgo(0, 0, 45),
    },
    {
      id: "pay_1004",
      orderId: "ord_1004",
      amount: 444,
      currency: "INR",
      status: PaymentStatus.PAID,
      method: "WALLET",
      transactionId: "pay_wlt_77491023",
      paidAt: daysAgo(0, 0, 10),
      createdAt: daysAgo(0, 0, 10),
      updatedAt: daysAgo(0, 0, 10),
    },
    {
      id: "pay_1005",
      orderId: "ord_1005",
      amount: 683,
      currency: "INR",
      status: PaymentStatus.PAID,
      method: "UPI",
      transactionId: "pay_upi_99210492",
      paidAt: daysAgo(1, 6),
      createdAt: daysAgo(1, 6),
      updatedAt: daysAgo(1, 6),
    },
    {
      id: "pay_1006",
      orderId: "ord_1006",
      amount: 529,
      currency: "INR",
      status: PaymentStatus.PAID,
      method: "CARD",
      transactionId: "pay_card_33091823",
      paidAt: daysAgo(2, 4),
      createdAt: daysAgo(2, 4),
      updatedAt: daysAgo(2, 4),
    },
    {
      id: "pay_1007",
      orderId: "ord_1007",
      amount: 910,
      currency: "INR",
      status: PaymentStatus.PAID,
      method: "UPI",
      transactionId: "pay_upi_66410928",
      paidAt: daysAgo(3, 8),
      createdAt: daysAgo(3, 8),
      updatedAt: daysAgo(3, 8),
    },
  ];

  const deliveries = [
    {
      id: "del_1001",
      orderId: "ord_1001",
      driverId: "drv_suresh",
      status: DeliveryStatus.DELIVERED,
      pickupAddress: "Shop 12, Galleria Mall, Sector 29",
      dropoffAddress: "Tower 4, Apt 802, Palm Springs, Golf Course Road, Gurugram",
      estimatedDistanceKm: 4.2,
      estimatedDurationMin: 22,
      createdAt: daysAgo(0, 4),
      updatedAt: daysAgo(0, 3),
    },
    {
      id: "del_1002",
      orderId: "ord_1002",
      driverId: "drv_arjun",
      status: DeliveryStatus.IN_TRANSIT,
      pickupAddress: "45 Cyber Hub, DLF Phase 2",
      dropoffAddress: "Villa 22, Magnolias, DLF Phase 5, Gurugram",
      estimatedDistanceKm: 6.5,
      estimatedDurationMin: 28,
      createdAt: daysAgo(0, 1),
      updatedAt: daysAgo(0, 0, 30),
    },
  ];

  const reviews = [
    {
      id: "rev_1",
      orderId: "ord_1001",
      vendorId: "ven_burger_hub",
      customerId: "usr_cust_1",
      rating: 5,
      comment: "Absolutely top notch burger! Arrived hot and juicy. The truffle mayo is heaven.",
      createdAt: daysAgo(0, 2),
      updatedAt: daysAgo(0, 2),
    },
    {
      id: "rev_2",
      orderId: "ord_1005",
      vendorId: "ven_burger_hub",
      customerId: "usr_cust_2",
      rating: 4,
      comment: "Crispy chicken was delicious and spicy! French fries were slightly cold but burger made up for it.",
      createdAt: daysAgo(1, 4),
      updatedAt: daysAgo(1, 4),
    },
    {
      id: "rev_3",
      orderId: "ord_1006",
      vendorId: "ven_napoli_pizza",
      customerId: "usr_cust_3",
      rating: 5,
      comment: "True Neapolitan pizza crust! Perfect charring and fresh cheese.",
      createdAt: daysAgo(2, 2),
      updatedAt: daysAgo(2, 2),
    },
  ];

  const auditLogs = [
    {
      id: "aud_1",
      userId: "usr_admin_1",
      action: "PLATFORM_INIT",
      entity: "SYSTEM",
      entityId: "SYSTEM",
      details: { message: "Standalone in-memory server initialized with pre-loaded mock stores" },
      ipAddress: "127.0.0.1",
      createdAt: daysAgo(1),
    },
    {
      id: "aud_2",
      userId: "usr_admin_1",
      action: "VENDOR_APPROVED",
      entity: "VENDOR",
      entityId: "ven_napoli_pizza",
      details: { vendorName: "Bella Italia Woodfired" },
      ipAddress: "127.0.0.1",
      createdAt: daysAgo(2),
    },
    {
      id: "aud_3",
      userId: "usr_admin_1",
      action: "SETTINGS_UPDATED",
      entity: "SETTING",
      entityId: "COMMISSION_RATE",
      details: { old: 12, new: 15 },
      ipAddress: "127.0.0.1",
      createdAt: daysAgo(3),
    },
  ];

  const platformSettings = [
    { id: "set_1", key: "commission_rate", value: "15", description: "Default vendor commission (%)", updatedAt: daysAgo(1) },
    { id: "set_2", key: "base_delivery_fee", value: "30", description: "Base delivery charge (INR)", updatedAt: daysAgo(1) },
    { id: "set_3", key: "per_km_fee", value: "10", description: "Per km delivery charge (INR)", updatedAt: daysAgo(1) },
    { id: "set_4", key: "max_delivery_radius_km", value: "15", description: "Maximum delivery radius (km)", updatedAt: daysAgo(1) },
    { id: "set_5", key: "platform_fee", value: "15", description: "Platform maintenance fee (INR)", updatedAt: daysAgo(1) },
    { id: "set_6", key: "emergency_mode", value: "false", description: "Platform emergency pause", updatedAt: daysAgo(1) },
    { id: "set_7", key: "currency", value: "INR", description: "Platform currency code", updatedAt: daysAgo(1) },
  ];

  const sessions = [
    {
      id: "sess_admin_demo",
      token: "demo-admin-session-token",
      userId: "usr_admin_1",
      expiresAt: new Date(now.getTime() + 86400000 * 30).toISOString(),
    },
  ];

  return {
    users,
    accounts,
    categories,
    vendors,
    products,
    drivers,
    orders,
    orderItems,
    payments,
    deliveries,
    reviews,
    auditLogs,
    platformSettings,
    sessions,
  };
}
