import { View, Text, TouchableOpacity, StyleSheet, ScrollView } from "react-native";
import { router } from "expo-router";
import { Ionicons } from "@expo/vector-icons";

export default function VendorSignUpScreen() {
  return (
    <ScrollView contentContainerStyle={styles.container}>
      <View style={styles.iconBox}>
        <Ionicons name="lock-closed" size={32} color="#7c3aed" />
      </View>

      <Text style={styles.heading}>Admin Creation Required</Text>
      <Text style={styles.subheading}>
        Vendor accounts cannot be registered from the mobile app. All vendor stores and login credentials are generated by System Administrators.
      </Text>

      <View style={styles.card}>
        <View style={styles.stepItem}>
          <Ionicons name="shield-checkmark-outline" size={20} color="#7c3aed" style={styles.stepIcon} />
          <Text style={styles.stepText}>Contact your system administrator to register your store.</Text>
        </View>
        <View style={styles.stepItem}>
          <Ionicons name="key-outline" size={20} color="#7c3aed" style={styles.stepIcon} />
          <Text style={styles.stepText}>Admin will create your vendor profile and login credentials.</Text>
        </View>
        <View style={styles.stepItem}>
          <Ionicons name="log-in-outline" size={20} color="#7c3aed" style={styles.stepIcon} />
          <Text style={styles.stepText}>Use those credentials to sign in and manage your restaurant.</Text>
        </View>
      </View>

      <TouchableOpacity
        style={styles.button}
        onPress={() => router.replace("/(auth)/login")}
        activeOpacity={0.8}
      >
        <Text style={styles.buttonText}>Return to Vendor Login</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 40,
    backgroundColor: "#f8f9fa",
  },
  iconBox: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: "#f5f3ff",
    borderWidth: 1,
    borderColor: "#ddd6fe",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  heading: {
    fontSize: 22,
    fontWeight: "700",
    color: "#111827",
    textAlign: "center",
    marginBottom: 8,
  },
  subheading: {
    fontSize: 14,
    color: "#6b7280",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 28,
  },
  card: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    marginBottom: 28,
    gap: 16,
  },
  stepItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  stepIcon: {
    marginRight: 12,
  },
  stepText: {
    flex: 1,
    fontSize: 13,
    color: "#374151",
    lineHeight: 18,
    fontWeight: "500",
  },
  button: {
    width: "100%",
    height: 48,
    borderRadius: 12,
    backgroundColor: "#7c3aed",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 15,
  },
});
